#!/usr/bin/env node
/*
 * Travel Vault — local encryption tool.
 * --------------------------------------
 * Reads the plaintext source-of-truth at assets/data.plain.js,
 * AES-256-GCM-encrypts it under a key derived from your master
 * password via PBKDF2 (200,000 iterations, SHA-256), and writes
 * the encrypted blob to assets/data.js.
 *
 * Usage (from the travel-vault/ directory or repo root):
 *   node travel-vault/encrypt.mjs
 *
 * The script prompts for the password with no echo. Your password
 * never leaves this machine; only the ciphertext is written out.
 *
 * For repeatable scripted runs (CI / re-encryption pipelines), set
 * the TRAVEL_VAULT_PASSWORD env var and the prompt is skipped.
 *
 * Workflow:
 *   1. Edit assets/data.plain.js to add/modify trips (gitignored).
 *   2. Run this script. assets/data.js is rewritten with new ciphertext.
 *   3. git add assets/data.js && git commit -m "..."
 */

import fs from 'node:fs';
import path from 'node:path';
import readline from 'node:readline';
import { fileURLToPath } from 'node:url';
import { webcrypto } from 'node:crypto';

// Node 18 doesn't expose globalThis.crypto by default; pin it.
const cryptoLib = globalThis.crypto ?? webcrypto;

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PLAIN_PATH = path.join(__dirname, 'assets', 'data.plain.js');
const OUT_PATH   = path.join(__dirname, 'assets', 'data.js');

const PBKDF2_ITERS = 200_000;
const KDF_HASH = 'SHA-256';
const SALT_BYTES = 16;
const IV_BYTES = 12;
const KEY_BITS = 256;
const VERSION = 1;

function readPasswordSilent(promptText) {
  return new Promise((resolve, reject) => {
    process.stdout.write(promptText);
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout, terminal: true });
    const stdin = process.stdin;
    let pw = '';
    const onData = (chunk) => {
      const c = chunk.toString('utf8');
      for (const ch of c) {
        if (ch === '') { // Ctrl-C
          process.stdout.write('\n');
          stdin.removeListener('data', onData);
          stdin.setRawMode(false); rl.close();
          reject(new Error('aborted'));
          return;
        }
        if (ch === '\n' || ch === '\r') {
          process.stdout.write('\n');
          stdin.removeListener('data', onData);
          stdin.setRawMode(false); rl.close();
          resolve(pw);
          return;
        }
        if (ch === '') { // backspace
          pw = pw.slice(0, -1);
        } else {
          pw += ch;
        }
      }
    };
    stdin.setRawMode(true);
    stdin.resume();
    stdin.on('data', onData);
  });
}

function extractVault(plainJsSource) {
  // The plain file is: `const VAULT = { ... };` plus comments.
  // Evaluate it in a tiny sandbox and grab the VAULT export.
  const factory = new Function(`${plainJsSource}\n; return VAULT;`);
  const v = factory();
  if (!v || typeof v !== 'object') {
    throw new Error('Could not read VAULT object from data.plain.js');
  }
  return v;
}

async function main() {
  if (!fs.existsSync(PLAIN_PATH)) {
    console.error(`error: ${PLAIN_PATH} not found.`);
    console.error('Create it (the gitignored source-of-truth) with the VAULT object before encrypting.');
    process.exit(1);
  }

  const plainSrc = fs.readFileSync(PLAIN_PATH, 'utf8');
  const vault = extractVault(plainSrc);
  const plaintextJson = JSON.stringify(vault);

  let password = process.env.TRAVEL_VAULT_PASSWORD;
  if (!password) {
    password = await readPasswordSilent('Master password: ');
    const confirm = await readPasswordSilent('Confirm password: ');
    if (password !== confirm) {
      console.error('error: passwords did not match.');
      process.exit(2);
    }
  }
  if (!password) {
    console.error('error: empty password.');
    process.exit(3);
  }

  const subtle = cryptoLib.subtle;
  const enc = new TextEncoder();

  const salt = cryptoLib.getRandomValues(new Uint8Array(SALT_BYTES));
  const iv   = cryptoLib.getRandomValues(new Uint8Array(IV_BYTES));

  const baseKey = await subtle.importKey('raw', enc.encode(password), 'PBKDF2', false, ['deriveKey']);
  const aesKey = await subtle.deriveKey(
    { name: 'PBKDF2', salt, iterations: PBKDF2_ITERS, hash: KDF_HASH },
    baseKey,
    { name: 'AES-GCM', length: KEY_BITS },
    false,
    ['encrypt'],
  );

  const ctBuf = await subtle.encrypt({ name: 'AES-GCM', iv }, aesKey, enc.encode(plaintextJson));
  const ctBytes = new Uint8Array(ctBuf);

  const b64 = (u8) => Buffer.from(u8).toString('base64');

  const header = `/*
 * Travel Vault — encrypted payload.
 * --------------------------------
 * Generated by travel-vault/encrypt.mjs. Do not edit by hand.
 * Edit travel-vault/assets/data.plain.js and re-run the script instead.
 *
 * Cipher: AES-256-GCM
 * KDF:    PBKDF2-HMAC-SHA-256, ${PBKDF2_ITERS.toLocaleString('en-US')} iterations
 */
`;

  const body = `window.VAULT_ENC = {
  v: ${VERSION},
  kdf: { name: 'PBKDF2', hash: '${KDF_HASH}', iterations: ${PBKDF2_ITERS} },
  cipher: 'AES-GCM',
  salt: '${b64(salt)}',
  iv:   '${b64(iv)}',
  ct:   '${b64(ctBytes)}'
};
`;

  fs.writeFileSync(OUT_PATH, header + body, 'utf8');

  console.log(`✓ Wrote ${path.relative(process.cwd(), OUT_PATH)}`);
  console.log(`  plaintext bytes:  ${plaintextJson.length}`);
  console.log(`  ciphertext bytes: ${ctBytes.length}`);
  console.log(`  trips encrypted:  ${vault.trips ? vault.trips.length : '?'}`);
}

main().catch((e) => {
  console.error('error:', e.message);
  process.exit(99);
});
